apiVersion: kctrl.carvel.dev/v1alpha1
kind: PackageBuild
metadata:
  creationTimestamp: null
  name: cliplugin.cli.tanzu.vmware.com
spec:
  release:
  - resource: {}
  template:
    spec:
      app:
        spec:
          deploy:
          - kapp: {}
          template:
          - ytt:
              paths:
              - cli.tanzu.vmware.com_cliplugins.yaml
          - kbld: {}
      export:
      - imgpkgBundle:
          image: gcr.io/eminent-nation-87317/tanzu-cli/test/crd/cliplugins
        includePaths:
        - cli.tanzu.vmware.com_cliplugins.yaml
        - .imgpkg/images.yml
